export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CHECK_USER_AUTH_ERROR = 'CHECK_USER_AUTH_ERROR';
export const CHECK_USER_AUTH_SUCCESS = 'CHECK_USER_AUTH_SUCCESS';

export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';
export const USER_LOGOUT_SUCCESSFUL = 'USER_LOGOUT_SUCCESSFUL';


export const RETRIEVE_NOTES_SUCCESS = 'RETRIEVE_NOTES_SUCCESS';
export const RETRIEVE_SINGLE_NOTE_SUCCESS = 'RETRIEVE_SINGLE_NOTE_SUCCESS';
